---
- name: "systemd_helper | Include prereq tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "systemd_helper | Include deploy tasks for systemd-resolved"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_resolved.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_resolved'] is defined"
    - "hostvars[inventory_hostname]['systemd_resolved'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-logind"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_logind.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_logind_logind', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-journald"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_journald.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_journald_settings', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-timesyncd"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_timesyncd.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_timedatectl_timesyncd',
      default='') not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-vconsole"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_vconsole.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_vconsole'] is defined"
    - "hostvars[inventory_hostname]['systemd_vconsole'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-tmpfiles"
  ansible.builtin.import_tasks:
    file: "exec.d/tmpfiles_executor.yml"
- name: "systemd_helper | Include deploy tasks for systemd-sysusers"
  ansible.builtin.import_tasks:
    file: "exec.d/sysusers_executor.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_sysusers_create',
      default='') not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-modules-load"
  ansible.builtin.include_tasks:
    file: "exec.d/modules_load_executor.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_modules_load_create',
      default='') not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-udev"
  ansible.builtin.include_tasks:
    file: "exec.d/udev_executor.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_udev_rules', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for systemd-networkd"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_networkd.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_networkd_networkd', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include deploy tasks for networkd profiles"
  ansible.builtin.include_tasks:
    file: "exec.d/networkd_executor.yml"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_networkd_interfaces', default='')
      not in ['', [], '[]', None]"
