---
- name: "systemd_helper | Stat systemd path"
  ansible.builtin.stat:
    path: "/etc/systemd"
  register: "systemd_helper_bin_stat"
- name: "systemd_helper | Assert that systemd path exists"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars',
        'systemd_helper_bin_stat')['stat']['exists'] == True"
    fail_msg: "/etc/systemd not exists, something wrong with this system"
    quiet: "true"
- name: "systemd_helper | Assert that ansible facts gathered successfully"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] is
        defined"
    fail_msg: "'ansible_facts' not found. Please enable facts gathering"
    quiet: "true"
- name: "systemd_helper | Assert that system manager is systemd"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] ==
        'systemd'"
    fail_msg: "System manager is not systemd"
    quiet: "true"
- name: "systemd_helper | Include prereq tasks for systemd-journald"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_journald.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_journald'] is defined"
    - "hostvars[inventory_hostname]['systemd_journald'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-logind"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_logind.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_logind'] is defined"
    - "hostvars[inventory_hostname]['systemd_logind'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-timedatectl"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_timedatectl.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_timesyncd'] is defined"
    - "hostvars[inventory_hostname]['systemd_timesyncd'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-tmpfiles"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_tmpfilesd.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_tmpfiles'] is defined"
    - "hostvars[inventory_hostname]['systemd_tmpfiles'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-sysusers"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_sysusersd.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_sysusers'] is defined"
    - "hostvars[inventory_hostname]['systemd_sysusers'] not in
      ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-modules-load"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_modules_load.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_modules_load'] is defined"
    - "hostvars[inventory_hostname]['systemd_modules_load']
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-udev"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_udev.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_udev'] is defined"
    - "hostvars[inventory_hostname]['systemd_udev'] not in ['', [], '[]', None]"
- name: "systemd_helper | Include prereq tasks for systemd-resolved"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_resolved.yml"
  when:
    - "not (systemd_resolved_mask | bool)"
    - "hostvars[inventory_hostname]['systemd_resolved'] is defined"
    - "hostvars[inventory_hostname]['systemd_resolved']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_resolved'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_resolved_make_link', default='')) == 'true'"
  vars:
    systemd_resolved_make_link: "[] | map(&make_link || 'false', @) | [0]"
- name: "systemd_helper | Include prereq tasks for systemd-networkd"
  ansible.builtin.include_tasks:
    file: "prereq.d/prereq_systemd_networkd.yml"
  when:
    - "hostvars[inventory_hostname]['systemd_networkd'] is defined"
    - "hostvars[inventory_hostname]['systemd_networkd'] not in
      ['', [], '[]', None]"
