---
- name: "systemd_helper | Restart systemd-journald service"
  ansible.builtin.systemd:
    name: "systemd-journald"
    state: "restarted"
  listen: "Restart systemd-journald"
- name: "systemd_helper | Restart systemd-logind service"
  ansible.builtin.systemd:
    name: "systemd-logind"
    state: "restarted"
  listen: "Restart systemd-logind"
- name: "systemd_helper | Restart systemd-timesyncd service"
  ansible.builtin.systemd:
    name: "systemd-timesyncd"
    state: "restarted"
  listen: "Restart systemd-timesyncd"
  when:
    - "hostvars[inventory_hostname]['systemd_timesyncd'] is defined"
    - "hostvars[inventory_hostname]['systemd_timesyncd']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_timesyncd'] |
      community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_timesyncd_restart', default='')) == 'true'"
  vars:
    systemd_timesyncd_restart: "[] | map(&restart || 'false', @) | [0]"
- name: "systemd_helper | Restart systemd-resolved service"
  ansible.builtin.systemd:
    name: "systemd-resolved"
    state: "restarted"
  listen: "Restart systemd-resolved"
  when:
    - "hostvars[inventory_hostname]['systemd_resolved'] is defined"
    - "hostvars[inventory_hostname]['systemd_resolved']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_resolved'] |
      community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_resolved_restart', default='')) == 'true'"
  vars:
    systemd_resolved_restart: "[] | map(&restart || 'false', @) | [0]"
- name: "systemd_helper | Restart systemd-networkd service"
  ansible.builtin.systemd:
    name: "systemd-networkd"
    state: "restarted"
  listen: "Restart systemd-networkd"
  when:
    - "hostvars[inventory_hostname]['systemd_networkd'] is defined"
    - "hostvars[inventory_hostname]['systemd_networkd']
      not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_networkd'] |
      community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_networkd_restart', default='')) == 'true'"
  vars:
    systemd_networkd_restart: "[] | map(&restart || 'false', @) | [0]"
- name: "systemd_helper | Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: "true"
  listen: "Reload systemd daemon"
