---
- name: "systemd_helper | Deploy resolved.conf"
  ansible.builtin.template:
    src: "systemd_resolved.j2"
    dest: "/etc/systemd/resolved.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart systemd-resolved"
- name: "systemd_helper | Flush handlers"
  ansible.builtin.meta: "flush_handlers"
- name: "systemd_helper | Enable systemd-resolved service"
  ansible.builtin.systemd:
    name: "systemd-resolved"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['systemd_resolved'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'systemd_resolved_enable', default='')) == 'true'"
  vars:
    systemd_resolved_enable: "[] | map(&enable || 'false', @) | [0]"
