---
- name: "systemd_helper | Deploy timesyncd.conf"
  ansible.builtin.template:
    src: "systemd_timesyncd.j2"
    dest: "/etc/systemd/timesyncd.conf"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  notify:
    - "Restart systemd-timesyncd"
- name: "systemd_helper | Enable systemd-timesyncd service"
  ansible.builtin.systemd:
    name: "systemd-timesyncd"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['systemd_timesyncd'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'systemd_timesyncd_enable', default='')) == 'true'"
  vars:
    systemd_timesyncd_enable: "[] | map(&enable || 'false', @) | [0]"
