---
- name: "systemd_helper | Include systemd-networkd profile deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_networkd_interfaces.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_networkd_interfaces'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
- name: "systemd_helper | Enable systemd-networkd service"
  ansible.builtin.systemd:
    name: "systemd-networkd"
    enabled: "yes"
  when:
    - "hostvars[inventory_hostname]['systemd_networkd'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_networkd_enable', default='')) == 'true'"
  vars:
    systemd_networkd_enable: "[] | map(&enable || 'false', @) | [0]"
