---
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [create]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_create'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  vars:
    query_type: "create"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_tmpfiles_create', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [clean]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_clean'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  vars:
    query_type: "clean"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_tmpfiles_clean', default='')
      not in ['', [], '[]', None]"
- name: "systemd_helper | Include systemd-tmpfiles deployment tasks [remove]"
  ansible.builtin.include_tasks:
    file: "deploy.d/deploy_tmpfiles.yml"
  loop: "{{ hostvars[inventory_hostname]['systemd_tmpfiles_remove'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "outer_item"
  vars:
    query_type: "remove"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_tmpfiles_remove', default='')
      not in ['', [], '[]', None]"
