---
- name: "systemd_helper | Make sysusers.d directory"
  ansible.builtin.file:
    path: "/etc/sysusers.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "systemd_helper | Set facts about sysusers.d"
  ansible.builtin.set_fact:
    systemd_sysusers_create:
      "{{ (hostvars[inventory_hostname]['systemd_sysusers'] |
      community.general.json_query('[].create[].file_name')) |
      ansible.builtin.unique() }}"
- name: "systemd_helper | Find exists sysusers configuration files"
  ansible.builtin.find:
    paths: "/etc/sysusers.d"
    recurse: "no"
    file_type: "file"
    use_regex: "yes"
    patterns: "(.*).conf"
    excludes: "{{ lookup('ansible.builtin.vars',
      'systemd_sysusers_exclude_create') }}"
  register: "systemd_sysusers_find_result"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_sysusers_exclude_create',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_modules_load'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_sysusers_drop_exists', default='')) == 'true'"
  vars:
    systemd_sysusers_drop_exists: "[] | map(&drop_exists || 'false', @) | [0]"
    systemd_sysusers_exclude_create: "{{ lookup('ansible.builtin.vars',
      'systemd_sysusers_create', default=[]) | map('regex_replace',
      '^(.*)$', '\\1.conf') | list() }}"
- name: "systemd_helper | Delete exists sysusers configuration files"
  ansible.builtin.file:
    path: "{{ systemd_sysusers_create_file['path'] }}"
    state: "absent"
  loop: "{{ lookup('ansible.builtin.vars',
    'systemd_sysusers_find_result')['files'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "systemd_sysusers_create_file"
    label: "{{ 'Remove ' + systemd_sysusers_create_file['path'] }}"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_sysusers_find_result')['files']
      is defined"
