---
- name: "systemd_helper | Stat resolv.conf path"
  ansible.builtin.stat:
    path: "/etc/resolv.conf"
  register: "systemd_resolv_link_stat"
- name: "systemd_helper | Delete resolv.conf because is file"
  ansible.builtin.file:
    path: "/etc/resolv.conf"
    state: "absent"
  when:
    - "lookup('ansible.builtin.vars',
      'systemd_resolv_link_stat')['stat']['exists']"
    - "not lookup('ansible.builtin.vars',
      'systemd_resolv_link_stat')['stat']['islnk']"
- name: "systemd_helper | Delete resolv.conf because is wrong link"
  ansible.builtin.file:
    path: "/etc/resolv.conf"
    state: "absent"
  when:
    - "lookup('ansible.builtin.vars',
      'systemd_resolv_link_stat')['stat']['exists']"
    - "lookup('ansible.builtin.vars',
      'systemd_resolv_link_stat')['stat']['islnk']"
    - "lookup('ansible.builtin.vars',
      'systemd_resolv_link_stat')['stat']['lnk_target'] !=
      '/var/run/systemd/resolve/resolv.conf'"
- name: "systemd_helper | Make symlink for systemd-resolved"
  ansible.builtin.file:
    src: "/var/run/systemd/resolve/resolv.conf"
    dest: "/etc/resolv.conf"
    state: "link"
    force: "yes"
    follow: "no"
