---
- name: "systemd_helper | Make networkd directory"
  ansible.builtin.file:
    path: "/etc/systemd/network"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "systemd_helper | Set facts about networkd"
  ansible.builtin.set_fact:
    systemd_networkd_networkd:
      "{{ hostvars[inventory_hostname]['systemd_networkd'] |
      community.general.json_query('[].networkd[]') }}"
    systemd_networkd_interfaces:
      "{{ (hostvars[inventory_hostname]['systemd_networkd'] |
      community.general.json_query('[].interfaces[].interface')) |
      ansible.builtin.unique() }}"
    systemd_networkd_vlans:
      "{{ (hostvars[inventory_hostname]['systemd_networkd'] |
      community.general.json_query('[].interfaces[].vlans[].name')) |
      ansible.builtin.unique() }}"
    systemd_networkd_macvlans:
      "{{ (hostvars[inventory_hostname]['systemd_networkd'] |
      community.general.json_query('[].interfaces[].vlans[].macvlans[].name')) |
      ansible.builtin.unique() }}"
- name: "systemd_helper | Make networkd all interfaces list"
  ansible.builtin.set_fact:
    systemd_networkd_interfaces_list: "{{ lookup('ansible.builtin.vars',
      'systemd_networkd_interfaces', default=[]) +
      lookup('ansible.builtin.vars', 'systemd_networkd_vlans', default=[]) +
      lookup('ansible.builtin.vars', 'systemd_networkd_macvlans',
      default=[]) }}"
- name: "systemd_helper | Find exists networkd configuration files"
  ansible.builtin.find:
    paths: "/etc/systemd/network"
    recurse: "no"
    file_type: "file"
    use_regex: "yes"
    patterns: "(.*).(network|netdev|link)"
    excludes: "{{ (lookup('ansible.builtin.vars',
      'systemd_networkd_exclude_interfaces_network', default=[]) +
      lookup('ansible.builtin.vars',
      'systemd_networkd_exclude_interfaces_netdev', default=[]) +
      lookup('ansible.builtin.vars', 'systemd_networkd_exclude_interfaces_link',
      default=[])) + ['99-default.link'] }}"
  register: "systemd_networkd_find_result"
  when:
    - "hostvars[inventory_hostname]['systemd_networkd'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_networkd_drop_exists', default='')) == 'true'"
  vars:
    systemd_networkd_drop_exists: "[] | map(&drop_exists || 'false', @) | [0]"
    systemd_networkd_exclude_interfaces_network:
      "{{ lookup('ansible.builtin.vars', 'systemd_networkd_interfaces_list',
      default=[]) | map('regex_replace', '^(.*)$', '\\1.network') | list() }}"
    systemd_networkd_exclude_interfaces_netdev:
      "{{ lookup('ansible.builtin.vars', 'systemd_networkd_interfaces_list',
      default=[]) | map('regex_replace', '^(.*)$', '\\1.netdev') | list() }}"
    systemd_networkd_exclude_interfaces_link:
      "{{ lookup('ansible.builtin.vars', 'systemd_networkd_interfaces_list',
      default=[]) | map('regex_replace', '^(.*)$', '\\1.link') | list() }}"
- name: "systemd_helper | Delete exists networkd configuration files"
  ansible.builtin.file:
    path: "{{ systemd_networkd_interface['path'] }}"
    state: "absent"
  loop: "{{ lookup('ansible.builtin.vars',
    'systemd_networkd_find_result')['files'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "systemd_networkd_interface"
    label: "{{ 'Remove file: ' + systemd_networkd_interface['path'] }}"
  when:
    - "lookup('ansible.builtin.vars',
      'systemd_networkd_find_result')['files'] is defined"
- name: "systemd_helper | Stat default networkd link settings"
  ansible.builtin.stat:
    path: "/etc/systemd/network/99-default.link"
  register: "systemd_networkd_default_link_stat"
- name: "systemd_helper | Mask default networkd link"
  ansible.builtin.file:
    path: "/etc/systemd/network/99-default.link"
    owner: "root"
    group: "root"
    mode: "0644"
    state: "touch"
  when:
    - "not lookup('ansible.builtin.vars',
      'systemd_networkd_default_link_stat')['stat']['exists']"
