---
- name: "systemd_helper | Make modules-load.d directory"
  ansible.builtin.file:
    path: "/etc/modules-load.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "systemd_helper | Set facts about modules-load.d"
  ansible.builtin.set_fact:
    systemd_modules_load_create:
      "{{ (hostvars[inventory_hostname]['systemd_modules_load'] |
      community.general.json_query('[].modules_load[].file_name')) |
      ansible.builtin.unique() }}"
- name: "systemd_helper | Find exists modules-load configuration files"
  ansible.builtin.find:
    paths: "/etc/modules-load.d"
    recurse: "no"
    file_type: "file"
    patterns: "(.*).conf"
    use_regex: "yes"
    excludes: "{{ lookup('ansible.builtin.vars',
      'systemd_helper_exclude_modules_load_create') }}"
  register: "systemd_helper_modules_load_find_result"
  when:
    - "lookup('ansible.builtin.vars', 'systemd_modules_load_create',
      default='') not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['systemd_modules_load'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'systemd_modules_load_drop_exists', default='')) == 'true'"
  vars:
    systemd_modules_load_drop_exists: "[] | map(&drop_exists || 'false', @) |
      [0]"
    systemd_helper_exclude_modules_load_create:
      "{{ lookup('ansible.builtin.vars', 'systemd_modules_load_create',
      default=[]) | map('regex_replace', '^(.*)$', '\\1.conf') | list() }}"
- name: "systemd_helper | Delete exists modules-load configuration files"
  ansible.builtin.file:
    path: "{{ systemd_modules_load_file['path'] }}"
    state: "absent"
  loop: "{{ lookup('ansible.builtin.vars',
    'systemd_helper_modules_load_find_result')['files'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "systemd_modules_load_file"
    label: "{{ 'Remove ' + systemd_modules_load_file['path'] }}"
  when:
    - "lookup('ansible.builtin.vars',
      'systemd_helper_modules_load_find_result')['files'] is defined"
