---
- name: "systemd_helper | Make tmpfiles.d directory"
  ansible.builtin.file:
    path: "/etc/tmpfiles.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "systemd_helper | Set facts about tmpfiles.d"
  ansible.builtin.set_fact:
    systemd_tmpfiles_create:
      "{{ (hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].create[].file_name')) |
      ansible.builtin.unique() }}"
    systemd_tmpfiles_clean:
      "{{ (hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].clean[].file_name')) |
      ansible.builtin.unique() }}"
    systemd_tmpfiles_remove:
      "{{ (hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].remove[].file_name')) |
      ansible.builtin.unique() }}"
- name: "systemd_helper | Find exists tmpfiles configuration files"
  ansible.builtin.find:
    paths: "/etc/tmpfiles.d"
    recurse: "no"
    file_type: "file"
    use_regex: "yes"
    patterns: "(.*).conf"
    excludes: "{{ lookup('ansible.builtin.vars',
      'systemd_tmpfiles_exclude_create') + lookup('ansible.builtin.vars',
      'systemd_tmpfiles_exclude_clean') + lookup('ansible.builtin.vars',
      'systemd_tmpfiles_exclude_remove') }}"
  register: "tmpfiles_find_result"
  when:
    - "hostvars[inventory_hostname]['systemd_tmpfiles'] |
       community.general.json_query(lookup('ansible.builtin.vars',
       'tmpfiles_drop_exists', default='')) == 'true'"
  vars:
    tmpfiles_drop_exists: "[] | map(&drop_exists || 'false', @) | [0]"
    systemd_tmpfiles_exclude_create: "{{ lookup('ansible.builtin.vars',
      'systemd_tmpfiles_create', default=[]) | map('regex_replace', '^(.*)$',
      '\\1.conf') | list() }}"
    systemd_tmpfiles_exclude_clean: "{{ lookup('ansible.builtin.vars',
      'systemd_tmpfiles_clean', default=[]) | map('regex_replace', '^(.*)$',
      '\\1.conf') | list() }}"
    systemd_tmpfiles_exclude_remove: "{{ lookup('ansible.builtin.vars',
      'systemd_tmpfiles_remove', default=[]) | map('regex_replace', '^(.*)$',
      '\\1.conf') | list() }}"
- name: "systemd_helper | Delete exists tmpfiles configuration files"
  ansible.builtin.file:
    path: "{{ systemd_tmpfiles_file['path'] }}"
    state: "absent"
  loop: "{{ lookup('ansible.builtin.vars', 'tmpfiles_find_result')['files'] |
    flatten(levels=1) }}"
  loop_control:
    loop_var: "systemd_tmpfiles_file"
    label: "{{ 'Remove file: ' + systemd_tmpfiles_file['path'] }}"
  when:
    - "lookup('ansible.builtin.vars', 'tmpfiles_find_result')['files'] is
      defined"
